#! /bin/bash
#
# This command works with
# - .html
# - .odt
#
# This command does not work with
# - .doc, .docx
# - .pdf
#
# Can be made to do so using calibre/libreoffice or any other number of tools
#


touch ./ai.input
less "$1" > ai.input 
cat ai.input | docker exec -i ollama ollama run llama3.2
rm ai.input
